#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Mon Nov  3 23:17:00 2025

add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/OV_NPU_PCIe.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/ddr3/ddr3.idf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/pcie_test/pcie_test.idf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/pll/pll.idf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/cmos_8_16bit.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/image_reshape.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/ips2l_pcie_dma.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/fifo/ipm_distributed_sdpram_v1_2_distributed_fifo.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/fifo/pgs_pciex4_fifo_v1_2.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ipm_distributed_sdpram_v1_2.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_expd_apb_mux.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_controller.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_cpld_tx_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_mrd_tx_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_mwr_tx_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/ips2l_pcie_dma_ram.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_ram/rtl/ipm2l_sdpram_v1_1_ips2l_pcie_dma_ram.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rd_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_cpld_wr_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_mwr_wr_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_rx_top.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tlp_rcv.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tlp_tx_mux.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_cpld_rd_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_mwr_rd_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_tx_top.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma_wr_ctrl.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/pgs_pciex4_prefetch_fifo_v1_2.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie_img_select.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/power_on_delay.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/reg_config.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/system_top.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/axi_crossbar_wrap_3x1_syn.adf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/axi_ctrl_outside_syn.adf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/axi_id_convertor_syn.adf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/npu_top_vcs_syn.adf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/axi_ctrl_outside.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/axi_crossbar_wrap_3x1.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/npu_top.v"
remove_design -force -verilog "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/pcie/pcie_dma_ctrl/ips2l_pcie_dma.v"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/axi_id_convertor.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/source/i2c_com.v"
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
synthesize -ads -selected_syn_tool_opt 2 
add_constraint "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/npu.fdc"
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/afifo_128i_128o_512/afifo_128i_128o_512.idf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/afifo_16i_128o_512/afifo_16i_128o_512.idf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/R_FIFO_128i_128o/R_FIFO_128i_128o.idf"
add_design "C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/W_FIFO_16i_128o/W_FIFO_16i_128o.idf"
remove_design -force C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/afifo_128i_128o_512/afifo_128i_128o_512.idf
remove_design -force C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/afifo_16i_128o_512/afifo_16i_128o_512.idf
remove_design -force C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/R_FIFO_128i_128o/R_FIFO_128i_128o.idf
remove_design -force C:/Users/realw/Desktop/npu/OV-PCIe/FPGA2025/ipcore/W_FIFO_16i_128o/W_FIFO_16i_128o.idf
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module OV_NPU_PCIe
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
