#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Wed Oct 29 14:14:44 2025

set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module test_ddr
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG484
compile -top_module test_ddr
